# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-module-test
  description: Testing terraform-example-module template
  homepage: https://cloudposse.com/accelerate
  topics: ""
