---
name: release-branch
on:
  pull_request_target:
    branches:
      - main
      - release/**
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches:
      - main
      - release/v*
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
      - 'test/**'
      - 'README.md'

permissions: {}

jobs:
  terraform-module:
    uses: cloudposse/.github/.github/workflows/shared-terraform-module.yml@shared-workflows
    secrets: inherit
