name: "Website Build Preview"

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  DEPLOYMENT_HOST: pr-${{ github.event.pull_request.number }}.atmos-docs.ue2.dev.plat.cloudposse.org

# These permissions are needed to interact with the GitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read

jobs:
  website-deploy-preview:
    # Do not deploy the website to the preview environment if the PR has the label 'website-no-deploy'
    if: ${{ !contains(github.event.*.labels.*.name, 'website-no-deploy') }}

    runs-on: ubuntu-latest

    environment:
      name: preview
      url: https://${{ env.DEPLOYMENT_HOST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies and Build Website
        run: |
          mkdir website/build
          touch website/build/content
          echo "Test Content" > website/build/content

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: website/build
          if-no-files-found: error
          retention-days: 1
