---
name: chatops
on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  id-token: write
  contents: write
  checks: write

jobs:
  test:
    uses: cloudposse/.github/.github/workflows/shared-terraform-chatops.yml@terratest-refactoring
    if: ${{ github.event.issue.pull_request }}
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}
