name: "Deploy Preview"

on:
  workflow_run:
    workflows: [Website Build Preview]
    types:
      - completed

env:
  PR_NUMBER: ${{ github.event.workflow_run.pull_requests.0.number }}
  DEPLOYMENT_HOST: pr-${{ github.event.workflow_run.pull_requests.0.number }}.atmos-docs.ue2.dev.plat.cloudposse.org

# These permissions are needed to interact with the GitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read

jobs:
  website-deploy-preview:
    # Do not deploy the website to the preview environment if the PR has the label 'website-no-deploy' or the workflow run failed
    if: ${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.workflow_run.pull_requests.*.labels.*.name, 'website-no-deploy')  }}
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: https://${{ env.DEPLOYMENT_HOST }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: website
          path: website/build
          run-id: ${{ github.event.workflow_run.id }}

      - name: Copy Website to S3 Bucket PR Folder
        run: |
          cd website/build
          ls -l ./
