name: "Deploy Preview"

on:
  workflow_run:
    workflows: [Website Build Preview]
    types:
      - completed

env:
  PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
  DEPLOYMENT_HOST: pr-${{ github.event.workflow_run.pull_requests[0].number }}.atmos-docs.ue2.dev.plat.cloudposse.org

# These permissions are needed to interact with the GitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read
  actions: read
  deployments: write

jobs:
  website-deploy-preview:
    # Do not deploy the website to the preview environment if the PR has the label 'website-no-deploy' or the workflow run failed
    if: ${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.workflow_run.pull_requests.*.labels.*.name, 'website-no-deploy')  }}
    runs-on: ubuntu-latest
    environment:
      name: release
#      url: https://${{ env.DEPLOYMENT_HOST }}

    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8
        id: deployment
        with:
          step: start
          env: preview
#          ref: ${{ github.event.workflow_run.pull_requests[0].number }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v1
        id: github-app
        with:
          app-id: ${{ vars.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}

      - run: |-
          echo '${{toJSON(github.event.workflow_run)}}'

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: website
          path: website/build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ steps.github-app.outputs.token }}

      - name: Copy Website to S3 Bucket PR Folder
        run: |
          cd website/build
          ls -l ./

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ env.DEPLOYMENT_HOST }}
          auto_inactive: true
