on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  terraform_module:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/feature-branch.yml@add_gate
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}
