name: Feature Branch
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]

permissions:
  pull-requests: read
  id-token: write
  contents: read

jobs:
  default:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/feature-branch.yml@shared_workflows
