name: Main Branch
on:
  pull_request:
    types: [closed]
    pull_request_target:
      types: [closed]
      branches:
        - main
      merged: true

permissions:
  contents: write
  id-token: write

jobs:
  default:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/main-branch.yml@shared_workflows
