name: Main Branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  terraform-module:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/main-branch.yml@shared_workflows
    secrets:
      github_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
