name: Main Branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  tf:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/main-branch.yml@shared_workflows
