name: release-branch
on:
  push:
    branches:
      - main
      - release/**

permissions:
  contents: write
  id-token: write

jobs:
  terraform-module:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/release-branch.yml@releases
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}
