---
name: release-published
on:
  release:
    types:
      - published

permissions: {}

jobs:
  terraform-module:
    uses: cloudposse/.github/.github/workflows/shared-release-branches.yml@shared-workflows
    secrets: inherit
