name: release-published
#on:
#  release:
#    types:
#      - published
on:
  workflow_run:
    workflows: [release-branch]
    types: [completed]

permissions:
  contents: write
  id-token: write

jobs:
  terraform-module:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/release.yml@releases
