name: scheduled
on:
  workflow_dispatch:  # Keeping this for testing: gh workflow run scheduled
  schedule:
    - cron: "30 0 * * *"


permissions:
  pull-requests: write
  id-token: write
  contents: write

jobs:
  scheduled:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/scheduled.yml@sched_workflows
